### ISSUE TITLE
Automatize tasks

### ISSUE THREAD

**Issue by jjimenezh** [sevtech-dev/cloud-storage-spring-api#2]
Automatize compilation and released in Artifactory with [Github Actions](https://help.github.com/es/actions/automating-your-workflow-with-github-actions/setting-up-continuous-integration-using-github-actions).
[Github Repo to deploy into Artifactory](https://github.com/samuelmeuli/action-maven-publish)

**Comment by migangqui** [comment]
Done in this [PR](https://github.com/sevtech-dev/cloud-storage-spring-api/pull/8)
